### ISSUE TITLE
Remove "Last Inning Outlines" link from calendar page

### ISSUE THREAD

**Issue by letakeane** [turingschool/front-end-curriculum#245]
There is a not-useful link that reads "Last Inning Outlines" at the bottom of the curriculum site's Daily Outlines page that should be removed.

![screenshot of bottom of Daily Outlines page with useless/outdated link](https://i.imgur.com/MCAJpUI.png)

[Link to page that displays issue](http://frontend.turing.io/today/)

**Comment by robbiejaeger** [comment]
Looks like this has been removed.
