### ISSUE TITLE
UI Needs massive overhaul (this is fake and for a lesson, please don't take seriously)

### ISSUE THREAD

**Issue by khalidwilliams** [turingschool/front-end-curriculum#419]
The front end site is not pink enough. The turing logo needs to pop much more. The buttons could be way more interactive. We need more animations. Easter eggs would be appreciated. This is as high priority.

**Comment by hannahhch** [comment]
I think the whole thing should be greyscale, but okay. Go ahead and make a PR and I'll check it out!
