### ISSUE TITLE
Update group project 1

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#579]
# Project to be updated: [M1 Ideabox](https://frontend.turing.edu/projects/module-1/ideabox-group-v2.html)

## Summary of changes needed: 
- The project refers to classes and methods in multiple places. Students will instead need to be pushed to use object literals and functions.
- The project either implicitly or explicitly states that students will need to create Idea and Comment classes. This will need to be changed.
- All group projects should make clear that a failure to participate can result in an individual failing the project, even if the project is otherwise passing

**Comment by hfaerber** [comment]
Updated index.html to point to correct updated project spec
