### ISSUE TITLE
Update final solo project 1

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#580]
# Project to be updated: [Tic Tac Toe](https://frontend.turing.edu/projects/module-1/tic-tac-toe-solo-v2.html)

## Summary of changes needed: 
- The project architecture expects the creation of Game and Player classes; students instead should be encouraged to make use of object literals.

**Comment by letakeane** [comment]
Ready for review: https://github.com/turingschool/front-end-curriculum/pull/600

**Comment by letakeane** [comment]
✅ Two reviewers ( @nicktu12 and @wvmitchell  )
✅ Comments addressed and code updated
✅ Changed base branch to `development` instead of `gh-pages`

Should be ready to move to **Queued for Merging**!

**Comment by wvmitchell** [comment]
Move it on over!!
