### ISSUE TITLE
Archive Classes lesson

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#583]
# Lesson to be archived: [JS Classes](https://frontend.turing.edu/lessons/module-1/js-classes.html)

## Reasoning for archive: 
- We're no longer going to be teaching Classes to M1 students

### Steps to take
- Move lesson to archive folder within M1 directory
- Remove classes lesson from website

**Comment by nicktu12** [comment]
https://github.com/turingschool/front-end-curriculum/pull/605
