### ISSUE TITLE
Update final solo project 2

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#586]
# Project to be updated: [Rock Paper Scissors](https://frontend.turing.edu/projects/module-1/rock-paper-scissors-solo-v2.html)

## Summary of changes needed: 
- The project architecture expects the creation of Player and Game classes; students should instead be pushed to use object literals and functions.

**Comment by hfaerber** [comment]
Relevant M1 notes from slack discussions: 

1. Function purity is a WOW for M1 projects, not an expectation.  Verbiage used in other projects is below

> Demonstrates efforts towards making functions pure when possible. *Note: Purity is not possible for every function in a FE application. Strive for it only when it makes sense.*


2. M1 students are not expected to use more than 1 JS file in projects (`main.js`).  In final project we can offer splitting the dom related js into a `domUpdates.js` file as an optional extension.  See TicTacToe updates for verbiage example.

**Comment by sertmer** [comment]
Thanks for the notes Heather!

**Comment by sertmer** [comment]
Here's the PR for the updates: 

https://github.com/turingschool/front-end-curriculum/pull/659
