### ISSUE TITLE
Update Connecting Data Model to the DOM

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#587]
# Lesson to be updated: [Connecting the Data Model to the DOM](https://frontend.turing.edu/lessons/module-1/javascript-connecting-the-data-model-to-the-dom.html)

## Summary of changes needed: 
- The last repo mentioned in the lesson asks students to look at an example repository that uses a Class to facilitate the Data Model. This example needs to be done without classes.

## Lesson creation guidelines (also on [FE Hub](https://www.notion.so/turingschool/Front-End-Team-Hub-50ee30a2e20e41109c188bd9827c2ca0)
- [Lesson Preparation Foundations](https://docs.google.com/document/d/1JbhMC94Dbw1OKmKucYZYKzQxio1kw-nq3RwU00G9ms4/edit)
- [4 Pillars of Remote Instruction](https://docs.google.com/document/d/1C8yy42yyXwF-JstQQzZed4mWIr4WgMB4AlM9-oz2XXE/edit)
- [Instructional Values](https://docs.google.com/document/d/1boFTy6ntSbvCKhf0VR-QH8UkUPuGJh8gDjuCd5YyL6g/edit)
- [Culturally Responsive Teaching](https://www.newamerica.org/education-policy/reports/culturally-responsive-teaching/)

**Comment by sertmer** [comment]
The Lesson itself has been merged to development, but the example repo has not, since it's still being used this inning.

**Comment by sertmer** [comment]
https://github.com/turingschool-examples/datamodel-dom/pull/1
https://github.com/turingschool/front-end-curriculum/pull/609

**Comment by wvmitchell** [comment]
Just moving this back for tracking purposes
