### ISSUE TITLE
Update JS Foundations documentation (Mythical Critters)

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#589]
# Activity to be updated: [JS Foundations](https://github.com/turingschool-examples/javascript-foundations)

## Summary of changes needed: 
- All of the class based exercises can remain in the repository, however they should be categorized as optional extras demanding independent study, and the Readme should reflect this

## Note

The repository for this issue is listed as front-end-curriculum, even though the repository is really [turingschool-examples/javascript-foundations](https://github.com/turingschool-examples/javascript-foundations). This is due to the fact that the project board cannot belong to more than one org (turingschool vs turingschool-examples)

**Comment by hfaerber** [comment]
Some mythicals have been revised to make FP.  Please do not archive the following suites to the optional extras folder:

- dragon
- vampire
- hobbit
