### ISSUE TITLE
Update weekly audits

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#593]
# Activity to be updated: [Weekly Audits Document](https://docs.google.com/document/d/1pQX88ofVzhEOOI0RqdJhMgpx_pFhtHVMC2ktHFwjHqo/edit)

## Summary of changes needed: 
- Activities for "Classes" and "Unit Testing Classes" should be removed
- Any topic that is taking the place of those (if applicable), should have an associated audit activity

**Comment by hfaerber** [comment]
- removed classes audit from Doc
- marked classes audit as (retired)
- deleted class reference question from Data Model vs DOM audit
- Removed Unit Testing Classes audit from Doc
- marked Unit Testing Classes audit as retired
-  Adding [Pure Functions audit](https://docs.google.com/forms/d/e/1FAIpQLSdj_Xxq5KmpVhBMulTyTkW76oFl0pxB53a8YmTLxBsoqmjWdQ/viewform)

**Comment by hfaerber** [comment]
Please review the [Pure Functions audit's](https://docs.google.com/forms/d/e/1FAIpQLSdj_Xxq5KmpVhBMulTyTkW76oFl0pxB53a8YmTLxBsoqmjWdQ/viewform) questions and provided answers. 

Currently I've placed the Pure Functions audit under Week 5.  It may need to be moved based on where we insert that lesson.

**Comment by CassandraGoose** [comment]
Love the 'red flags' question so much. 

Is Example 3 supposed to be a different code snipped? It looks like it's the 'fruit' example again.

**Comment by hfaerber** [comment]
Oh boy!  Thanks for catching that Cass!  I've switched it out with the correct example.   Moving to Merged To Development since this is easily, infinitely iterable.
