### ISSUE TITLE
Update Array prototypes lesson

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#594]
# Lesson to be updated: [Array Prototypes](https://frontend.turing.edu/lessons/module-1/js-array-prototype-methods.html)

## Summary of changes needed: 
- Currently this lesson is being utilized as a 'self-teach' activity
- Given our new functional emphasis, it makes sense to have an actual lesson on this
- Review the lesson creation guidelines, and ensure that the lesson plan meets those criteria

## Lesson creation guidelines (also on [FE Hub](https://www.notion.so/turingschool/Front-End-Team-Hub-50ee30a2e20e41109c188bd9827c2ca0)
- [Lesson Preparation Foundations](https://docs.google.com/document/d/1JbhMC94Dbw1OKmKucYZYKzQxio1kw-nq3RwU00G9ms4/edit)
- [4 Pillars of Remote Instruction](https://docs.google.com/document/d/1C8yy42yyXwF-JstQQzZed4mWIr4WgMB4AlM9-oz2XXE/edit)
- [Instructional Values](https://docs.google.com/document/d/1boFTy6ntSbvCKhf0VR-QH8UkUPuGJh8gDjuCd5YyL6g/edit)
- [Culturally Responsive Teaching](https://www.newamerica.org/education-policy/reports/culturally-responsive-teaching/)

**Comment by CassandraGoose** [comment]
I can't get this issue to link to the PR for some reason. The PR for this issue is: https://github.com/turingschool/front-end-curriculum/pull/622
