### ISSUE TITLE
Update Extra Practice Hub

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#596]
# Activity to be updated: [Extra Practice Hub](https://frontend.turing.edu/lessons/module-1/extra-practice.html)

## Summary of changes needed: 
- Many broken links here, update/remove as necessary, find them using the Integrity tool
- Remove any exercises involving Classes, replace with other activities as necessary

**Comment by kaylagordon** [comment]
I merged this into gh-pages b/c I want the current students to benefit from the fixed links.
