### ISSUE TITLE
Update Final React Assessment 2 (URL Shortener)

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#629]
# Assesment to be updated: [Final Assessment: URL shortener](https://github.com/turingschool-examples/url-shortener-ui)

## Summary of changes needed: 
- The current starting repo uses a class-based component structure
- This needs to be transitioned to functional components

## Competencies to be demonstrated
- The overall competencies are the same, however a successful final assessment will demonstrate the use of hooks to store and update state in the application, as well as pull information from the API

## Note
- The associated repo for this ticket is front-end-curriculum, but all the necessary changes will actually happen in the repo linked above
- Please make sure to link your PR in a comment below

**Comment by hfaerber** [comment]
This assessment isn't needed until our 2nd inning of teaching FP in M3.  Please complete the other more time-sensitive M3 tickets before choosing this one.

**Comment by hfaerber** [comment]
[PR](https://github.com/turingschool-examples/url-shortener-ui/pull/43) is ready for review
