### ISSUE TITLE
Update REST lesson

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#635]
# Lesson to be updated: [REST Architecture](https://frontend.turing.edu/lessons/module-3/rest-architecture-and-urls.html)

## Summary of changes needed: 
- The M3 team has identified that this lesson lacks focus
- Assess the learning goals of the lesson, and taking into account the lesson creation guidelines below, update the lesson plan to better focus around those learning goals

## Lesson creation guidelines (also on [FE Hub](https://www.notion.so/turingschool/Front-End-Team-Hub-50ee30a2e20e41109c188bd9827c2ca0))
- [Lesson Preparation Foundations](https://docs.google.com/document/d/1JbhMC94Dbw1OKmKucYZYKzQxio1kw-nq3RwU00G9ms4/edit)
- [4 Pillars of Remote Instruction](https://docs.google.com/document/d/1C8yy42yyXwF-JstQQzZed4mWIr4WgMB4AlM9-oz2XXE/edit)
- [Instructional Values](https://docs.google.com/document/d/1boFTy6ntSbvCKhf0VR-QH8UkUPuGJh8gDjuCd5YyL6g/edit)
- [Culturally Responsive Teaching](https://www.newamerica.org/education-policy/reports/culturally-responsive-teaching/)

**Comment by nicktu12** [comment]
https://github.com/turingschool/front-end-curriculum/pull/717
