### ISSUE TITLE
Update Ideabox difficulty

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#669]
## Description

The current Ideabox project is not of equal difficulty of the Colorandom project that it is rotated with. The project needs to be updated so the difficulty of the two projects is more aligned.

## Tasks

* Iterations need to be self contained, only requiring work from students that is necessary for the features of that iteration
* Currently several of the early iterations demand that students do work that is necessary for later iterations, and the students never end up getting to those later iterations
* Every iteration should be more like a collection of self-contained tickets, where each ticket can stand alone as a feature (potentially requiring some amount of HTML, CSS, and JavaScript)

**Comment by kaylagordon** [comment]
ready for review: https://github.com/turingschool/front-end-curriculum/pull/682
