### ISSUE TITLE
Updates to What's Cooking Part II

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#676]
## Description of changes
Update the rubric to more closely align with the M1 style.  Can you other already updated M2 projects as a guide for consistency.

- Spec does not reference classes and was recently updated through Robbie's agile work so all we need to do is noted below.

## Criteria
- Be sure to add these rubric competency examples:

> * Demonstrates efforts towards making functions pure when possible. Note: Purity is not possible for every function in a FE application. Strive for it only when it makes sense.
> * WOW option: Effectively implements one or more closure throughout project. Note: See Closures lesson on M2 lesson page as a resource.

- Add this verbiage to bottom of rubric:

> ### Collaboration and Professionalism
> * See "Minimum Collaboration and Professionalism Expectations" above.
> * While this is not a scored rubric section, every team member is expected to fully participate, contribute, communicate and collaborate with the team throughout the entirety of this project. Failure to do so can result in an individual failing the project, even if the group/project is otherwise passing."

- Add scoring outline to rubric

> <section class="answer">
> ### Does the project demonstrate student understanding of the learning goals & concepts?
> Projects will answer that question, being marked as yes, not yet, and wow. Similarly, each section of the rubric (see below) will have yes/not yet/wow markings, helping you understand your progress and growth in specific areas.
> The overall project outcome (yes, not yet, wow) is determined by “averaging” each section’s outcome. You can think of a “yes” being worth a 1, a “not yet” being worth a 0, and a “wow” being worth a 2.
> For this project, an average of 0.5 is considered a yes - a passing project that demonstrates good student understanding! An average of 1+ is considered a wow. Anything below a 0.5 is considered a not yet - a project that indicates that the concepts have not been fully understood (see note in the section below).
> </section>

**Comment by hfaerber** [comment]
PR ready for review [here](https://github.com/turingschool/front-end-curriculum/pull/688)
