### ISSUE TITLE
Update final solo projects

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#729]
# Project to be updated: [Overlook](https://frontend.turing.edu/projects/overlook.html) & [Travel Tracker](https://frontend.turing.edu/projects/travel-tracker.html)

## Summary of changes needed: 
- Accessibility testing needs to be a specified criteria for passing the final project
- The rubrics needs to be updated
- The rubrics should specify that students are expected to use lighthouse in chrome, while in snapshot mode

**Comment by nicktu12** [comment]
https://github.com/turingschool/front-end-curriculum/pull/733
